### ISSUE TITLE
can not open menu in normal model, but in debug model it is regular

### ISSUE THREAD

**Issue by oillamp** [jaysoo/react-native-menu#10]
in normal model , the tap event looks like no effect, do not know why

**Comment by oillamp** [comment]
after some observe i find the question is that : i use your Example/example.js, and  if i use a Navigator and the navigator`s initialRoute  to render the example, that is correct, besides that, if use the navigator.push  render it, the menu could not toggle visible. it is strange that in debuger model the menu is correct!

you can see the error in  https://github.com/oillamp/react-native-menu-example

you can change the line, to literal replication

`
initialRoute={{name: 'launchpad'}}
/*initialRoute={{name: 'example'}} */
`

please help me, thanks a lot.

**Comment by oillamp** [comment]
i use navigator.replacePrevious to replace the current sence, it is corrent.

looks like if the sence is top of the router stack , it will be ok .

is there some rely on router stack ?

**Comment by linefeedse** [comment]
I can confirm this problem. In iOS simulator everything works as advertised, but on a real device (iphone 6), If a navigator route is pushed, the menu does not pop up. If route is replaced, it works fine.
