### ISSUE TITLE
Edge detection: avoiding screen overflow

### ISSUE THREAD

**Issue by mschipperheyn** [jaysoo/react-native-menu#13]
I really like this component. However, if you use on a component that is close to the left edge of the screen, the dropdown will overflow the screen.

The expected behaviour in this case would be that the dropdown would behave more like a "long press" context menu, and appear over the trigger in a way that displays the entire menu visibly.

**Comment by bawn** [comment]
+1

I am use [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) to config my scene，detail info follow gif

![12](https://cloud.githubusercontent.com/assets/7238866/14346426/c9808486-fce4-11e5-8793-1c4dc01c057f.gif)

**Comment by CodeTitanian** [comment]
+1
I have the same problem but in my case, my trigger button in positioned low in the screen and when the menu opens up - it is half visible. Part of it is rendered below the screen edge...

**Comment by anativ** [comment]
+1

**Comment by dovfrank** [comment]
+1

**Comment by JamesHollyer** [comment]
+1 yup I am having the same issue.  I tried using styles and adding margins but could only manage to more the text inside the dropdown and not the dropdown box.  Other than that it is working great!  Thanks

**Comment by sodik82** [comment]
for some of you following "drop-in" replacement could be interesting https://github.com/instea/react-native-popup-menu
_disclaimer: I am affiliated with that lib._

**Comment by hiteshsahu** [comment]
Same Issue Android

![image](https://user-images.githubusercontent.com/4076925/30028584-43a8800c-91a3-11e7-886f-9307caa53124.png)

After Rotation

![image](https://user-images.githubusercontent.com/4076925/30028623-6ab768ca-91a3-11e7-808d-401142500ada.png)
