### ISSUE TITLE
menu not positioned correctly

### ISSUE THREAD

**Issue by jurgenphotek** [jaysoo/react-native-menu#16]
Hi,

When using components that slide in, the menu appears in the wrong location. looking into this, it is relying on px, py of the component. In my case the component slides in from the side so the px is wrong.

thanks

**Comment by JosephDev** [comment]
I have the same problem with @jurgenphotek with [react-native-drawer](https://github.com/root-two/react-native-drawer)

After open the drawer, menu is sticked on the drawer not as expected position.

**Comment by JosephkimOS** [comment]
I fixed this problem waiting until drawer has been closed. now it render correct position.

**Comment by JosephDev** [comment]
I fixed this problem waiting until drawer has been closed. now it render correct position.
@jurgenphotek please check my PR with this problem.
