### ISSUE TITLE
Menu shows up behind Modal

### ISSUE THREAD

**Issue by mschipperheyn** [jaysoo/react-native-menu#17]
Hi,

I'm trying to implement the context menu in a Modal. I find that when I click the trigger, the options menu appears behind the modal for some reason.

**Comment by chinalwb** [comment]
Any solution to this issue? I am running into the same issue.

Thanks.

**Comment by mschipperheyn** [comment]
I don't remember this one. But you could simply place it higher in the hierarchy and hook it up to some Context variable.

**Comment by chinalwb** [comment]
Thanks. I didn't study much of the source code for how to hook the context menu. But I think that is the correct solution. So my solution was to replace the Modal to a View.
