### ISSUE TITLE
Cannot read property 'shape' of undefined

### ISSUE THREAD

**Issue by demiro** [jaysoo/react-native-menu#18]
Getting this error on react-native 0.26

![screenshot_20160531-085755](https://cloud.githubusercontent.com/assets/514682/15667643/48b0d87e-270f-11e6-8797-96a6ac6137f0.png)

**Comment by sodik82** [comment]
most likely related to the breaking change in RN 0.26. However you can try https://github.com/instea/react-native-popup-menu (should have same API)
_disclaimer - I am associated with that lib_

**Comment by demiro** [comment]
to be honest I have, and I am using it... but it's very buggy.... when I click on it, sometimes it doesn't close all the way down (stays a dot, or like very small)

**Comment by sodik82** [comment]
issue reports are welcomed. if you have any screenshots or even better (not) working examples. or anything special in your setup (is it happening during debugging or also in release version on real device).

**Comment by KaanErkol** [comment]
+1

**Comment by johnmurphy01** [comment]
Is there no way to fix react-native-menu to work with RN > 0.26? That would be the ideal situation for me. I switched to react-native-popup-menu but I think it's causing more problems than it's worth.

**Comment by Arkanine** [comment]
I have the same issue after upgrade react-native

**Comment by daiyunchao** [comment]
@Arkanine +1
