### ISSUE TITLE
undefined is not an object (evaluating '_React$PropTypes.shape')

### ISSUE THREAD

**Issue by dimonomid** [jaysoo/react-native-menu#20]
Hello,

I'm trying to use your module in React Native 0.26.3, but just when I import anything from `react-native-menu`, I get this:

```
undefined is not an object (evaluating '_React$PropTypes.shape')
```

Could you please give some clue?

**Comment by Arkanine** [comment]
Hi, I have the same error after react-native upgrade from 0.25  to 0.30.

**Comment by AgtLucas** [comment]
Try import `PropTypes`, something like this:

```javascript
// Import PropTypes
import React, { Component, PropTypes } from 'react'
// The other "things" you need from react-native...
import {
  Image,
  Text,
   ...
} from 'react-native'
```
