### ISSUE TITLE
Click the outside of Menu,Cannot close the Menu

### ISSUE THREAD

**Issue by NancyZY** [jaysoo/react-native-menu#21]
When I Clicked the outside of Menu, I want to close the menu, but  I don't know how to deal with it.

**Comment by JosephDev** [comment]
@NancyZY I have the same trouble. Did you find a solution?

**Comment by JosephDev** [comment]
same here

**Comment by atinder** [comment]
+1

**Comment by knapeto** [comment]
any solution?

**Comment by Scimonster** [comment]
I think `<MenuContext>` has to surround everything in order for it to listen for taps and close the menu.

**Comment by MaxShv** [comment]
+1

**Comment by swaroopa94** [comment]
Have the same issue how Can I solve it any answers?

**Comment by fabriziomoscon** [comment]
this works for me with version `0.23.0` and using RN `0.46.4`
