### ISSUE TITLE
undefined is not an object('_React$PropTypes.shape')

### ISSUE THREAD

**Issue by mvnpgh** [jaysoo/react-native-menu#22]
@jaysoo 
![screenshot_20160727-112507](https://cloud.githubusercontent.com/assets/20180149/17165308/1407e2b0-53ed-11e6-823f-7299b363f6b8.png)

Recently we upgrade the React@15.0.2 and react-native@30.0.
After that we are getting the issue.
the below is the screen shot
Thx

**Comment by aestrro** [comment]
Yeah I'm getting the same

**Comment by bencodezen** [comment]
Haven't seen any update on this thread, but I'm seeing the same thing as well for React@16.0.0-alpha.12 and react-native@0.47.0

**Comment by marcmoo** [comment]
samething happens here, doing a app using react-native-maps
