### ISSUE TITLE
Menu not positioned correctly inside scrollview

### ISSUE THREAD

**Issue by danleveille** [jaysoo/react-native-menu#25]
When this menu is inside a scrollview, it works fine on the initial load, but once tapped after you've scrolled within its container, it does not position correctly. 

Example:
![screen shot 2016-09-19 at 8 10 23 pm](https://cloud.githubusercontent.com/assets/5267075/18656434/e2c55f1e-7ea5-11e6-9fed-5f6a96bbbea9.png)

**Comment by zhang699** [comment]
@danleveille 
My solution is put `<MenuContext>` outside the `<ScrollView>`

```
<MenuContext>
  <ScrollView>
      ... your stuff here
     <Menu>
      ... your menu trigger and options
      </Menu>
  </ScrollView>
</MenuContext>
```

after scrolled, the menu still appear near your menu trigger.

**Comment by lavarajallu** [comment]
In menu Context you just give 

```
<MenuContext lazyRender={200}>
    
</MenuContext>

```
What ever you give allignment fixed
