### ISSUE TITLE
How can i call isMenuOpen() for MenuContext?

### ISSUE THREAD

**Issue by Pegahkeshavarz** [jaysoo/react-native-menu#27]

**Comment by tbloncar** [comment]
@Pegahkeshavarz: You can accomplish this via a ref to the context; shown in the example [here](https://github.com/jaysoo/react-native-menu/blob/master/Example/Example.js#L21). I have something like this:

``` js
<MenuContext ref={context => this.menuContext = context}>
  <Menu name='rightMenu'>
    ...
  </Menu>
<MenuContext>
```

You can get then leverage the documented methods from the reference:

``` js
this.menuContext.openMenu('rightMenu')
```

**Comment by joncursi** [comment]
How do you accomplish this when `MenuContext` is not present in the same file that `this.menuContext.openMenu(...)` is being called?

My `MenuContext` is way up in the component tree, so calling `this.menuContext.closeMenu(...)` results in:

Error: Cannot read property 'closeMenu' of undefined

**Comment by joncursi** [comment]
For anyone else that arrives here, this issue can be addressed if you migrate over to `react-native-popup-menu` and use the declarative, controlled menu:

https://github.com/instea/react-native-popup-menu/blob/master/doc/examples.md#declarative-menu
