### ISSUE TITLE
Menu menu-1 has already been registered in this context?

### ISSUE THREAD

**Issue by xiongpinli** [jaysoo/react-native-menu#29]
点击的时候，就会出现这种错误，我自己提供别的名字也会出这个，这是什么原因

**Comment by DeDuckProject** [comment]
Seems to be fixed in 0.20.2

**Comment by Yorkey** [comment]
<View style={this.props.style} ref={this._register} collapsable={false}>
I find _register called again when component will unmount,It calls this warn.

**Comment by Yorkey** [comment]
In _registerMenu(name, hooks) when hooks.ref is null, should not register!
