### ISSUE TITLE
Combining with ListView

### ISSUE THREAD

**Issue by avishayil** [jaysoo/react-native-menu#3]
Hi,
I'd like to combine the menu functionality with listview, to make the menu look like a context menu.
I tried to get started with your example, here's the relevant code:

``` javascript
<MenuContext style={{ flex: 1 }}>
    <ListView
    ref="listview"
    key={"postList"}
    dataSource={this.state.dataSource}
    renderSectionHeader={this.renderSectionHeader}
    renderRow={this.renderArticle}
        />
</MenuContext>
```

And the renderArticle function code:

``` javascript
<View style={styles.articleView}>
    <View style={styles.articleViewMeta}>
        <Text style={styles.articleViewMetaTitle}>{article.title}</Text>
        <View style={{flex: 1, flexDirection: 'row', justifyContent: 'space-between'}}>
            <View style={{ padding: 10, flexDirection: 'row', backgroundColor: 'pink' }}>

                <Menu onSelect={(value) => alert(`User selected the number ${value}`)}>
                <MenuTrigger>
                    <Text style={{ fontSize: 20 }}>&#8942;</Text>
                </MenuTrigger>
                <MenuOptions>
                    <MenuOption value={1}>
                    <Text>One</Text>
                    </MenuOption>
                    <MenuOption value={2}>
                    <Text>Two</Text>
                    </MenuOption>
                </MenuOptions>
                </Menu>
            </View>
            <Text style={styles.articleViewMetaAuthor}>{article.author}</Text>
        </View>
    </View>
    <Image source={{uri: article.image}} style={styles.articleViewImage} />
</View>
```

I can see the MenuTrigger on the right place, but I can't see the menu when pressing on the trigger.
Any suggestions?

**Comment by jaysoo** [comment]
@avishayil Thanks for the report. I'll have to take a look last in the week when I have some free time.

It should either be:
1. The calculation of the menu position is wrong.
2. The position is cached and not refreshed.

**Comment by avishayil** [comment]
Sure, let me know if you need any help.

**Comment by jaysoo** [comment]
@avishayil The issue was that multiple menus under the same context needed an unique name to be provided. This has been changed so unique identifiers will be generated for you automatically.

Can you give `0.18.15` a shot and let me know if this fixes your problem?

**Comment by avishayil** [comment]
Thanks, I'll try it and report back.

**Comment by avishayil** [comment]
It seems to solve this particular issue :>
I have another question. How can I decide on the placement of the options container? I tried to play with the styles but the menu always goes out of the screen:
![Menu is on the left side, how to move it right?](http://i.imgur.com/9YnhHfO.png)

**Comment by jaysoo** [comment]
@avishayil I haven't added the option to change positioning yet. It's on my TODO list.

**Comment by avishayil** [comment]
Thanks!

-- 
Avishay Bassa
Sent with Airmail

On March 1, 2016 at 3:53:35 PM, Jack Hsu (notifications@github.com) wrote:

@avishayil I haven't added the option to change positioning yet. It's on my TODO list.
