### ISSUE TITLE
Menu not position correctly

### ISSUE THREAD

**Issue by dzenkovich** [jaysoo/react-native-menu#30]
![image](https://cloud.githubusercontent.com/assets/2685498/19606570/e715a2d8-97cb-11e6-992b-8056bb27eba2.png)

I'm using [react-native-router-flux](https://github.com/aksonov/react-native-router-flux) to toggle between app scenes, after a transition when I try to click on the toggle menu is displayed offscreen at the opposite side (left instead of right)

Any idea or advice? I've tried various combinations of flex layouts on MenuContext and Menu but no luck.

**Comment by fedevitch** [comment]
I have the same issue
css fixes also not helps

**Comment by denys-ostapenko** [comment]
Does anybody know how to fix this issue?

**Comment by thanhlmm** [comment]
try our repo https://github.com/nlug/react-native-menu
Read the "Important 2"

**Comment by chavhan-kunal** [comment]
this solved my issue

**Comment by chmiguel** [comment]
i has used  <MenuOptions  optionsContainerStyle={{margin: 56, position: 'absolute', left: (window.width - 270), elevation: 20 }} renderOptionsContainer={(options) =><SessionsMenu />}> with a custom component and this has solved the problem
