### ISSUE TITLE
Android Menu Flash

### ISSUE THREAD

**Issue by eggeggeg** [jaysoo/react-native-menu#32]
I run example code
Android menu click will flash,but IOS is no problem

https://drive.google.com/file/d/0Bx3lBHD5BXi-Q2ZCUHVRX2s3MkU/view?usp=sharing

"react-native": "0.33.0",
"react-native-menu": "^0.20.2",

**Comment by tchamio** [comment]
i'm getting the same issue after upgrading react native to 0.37.0

**Comment by johnygomez** [comment]
I've got the same problem, any solutious yet?

**Comment by sodik82** [comment]
we have solved "same" problem by https://github.com/instea/react-native-popup-menu/commit/ce85522cd82466fda71eae3ad530eac4ce361082

might help as well.

**Comment by jasonlvg** [comment]
@sodik82 thanks, it works!!!

**Comment by tchamio** [comment]
it works for me too. thanks !!

**Comment by bryaneaton13** [comment]
I just opened up a PR to fix the issue by making the change the @sodik82 recommended.
https://github.com/jaysoo/react-native-menu/pull/33

**Comment by LeoAref** [comment]
@sodik82 Could you review and merge that PR #33 
It's really a frustrating bug!

**Comment by smilingkylan** [comment]
@sodik82 I don't fully understand where I make that change in the code. My /node_modules directory does not have "react-native-menu-pulldown" anywhere in it, and 'node_modules/react-native-menu' does not have a src/renderers folder.

**Comment by ndbroadbent** [comment]
@kylanhurt - that fix was for a different project that was experiencing the same issue. This is how to apply the fix to this project: https://github.com/jaysoo/react-native-menu/pull/33/files

You can use @bryaneaton13's branch in the meantime. Add to your `package.json`:

```
"react-native-menu": "bryaneaton13/react-native-menu#patch-1"
```

**Comment by samanthacampisi** [comment]
Please merge @bryaneaton13's branch. The bug looks really annoying.
