### ISSUE TITLE
Menu throws an error after latest upgrade (RN 0.44)

### ISSUE THREAD

**Issue by laylafy** [jaysoo/react-native-menu#41]
I have recently upgraded my React Native to the latest version (0.44) which seems to have broken this component.
Just including something as basic as `<Menu></Menu>` would give the following:

`undefined is not an object (evaluating 'this.context.menuController.makeName')

Menu_componentWillMount
    makeMenu.js:34:66
measureLifeCyclePerf
    ReactCompositeComponent.js:63:11
mountComponent
    ReactCompositeComponent.js:322:10
mountComponent
    ReactReconciler.js:57:6
mountChildren
    ReactMultiChild.js:277:10
initializeChildren
    ReactNativeBaseComponent.js:67:41
mountComponent
    ReactNativeBaseComponent.js:173:6
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
mountChildren
    ReactMultiChild.js:277:10
initializeChildren
    ReactNativeBaseComponent.js:67:41
mountComponent
    ReactNativeBaseComponent.js:173:6
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
mountChildren
    ReactMultiChild.js:277:10
initializeChildren
    ReactNativeBaseComponent.js:67:41
mountComponent
    ReactNativeBaseComponent.js:173:6
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
mountChildren
    ReactMultiChild.js:277:10
initializeChildren
    ReactNativeBaseComponent.js:67:41
mountComponent
    ReactNativeBaseComponent.js:173:6
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
mountChildren
    ReactMultiChild.js:277:10
initializeChildren
    ReactNativeBaseComponent.js:67:41
mountComponent
    ReactNativeBaseComponent.js:173:6
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
mountChildren
    ReactMultiChild.js:277:10
initializeChildren
    ReactNativeBaseComponent.js:67:41
mountComponent
    ReactNativeBaseComponent.js:173:6
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
performInitialMount
    ReactCompositeComponent.js:516:6
mountComponent
    ReactCompositeComponent.js:347:8
mountComponent
    ReactReconciler.js:57:6
updateChildren
    ReactChildReconciler.js:165:10
_reconcilerUpdateChildren
    ReactMultiChild.js:223:10
_updateChildren
    ReactMultiChild.js:366:6
updateChildren
    ReactMultiChild.js:352:25
receiveComponent
    ReactNativeBaseComponent.js:118:24
receiveComponent
    ReactReconciler.js:158:38
_updateRenderedComponentWithNextElement
    ReactCompositeComponent.js:1140:8
_updateRenderedComponent
    ReactCompositeComponent.js:1111:6
_performComponentUpdate
    ReactCompositeComponent.js:1032:36
updateComponent
    ReactCompositeComponent.js:915:8
receiveComponent
    ReactCompositeComponent.js:745:6
receiveComponent
    ReactReconciler.js:158:38
updateChildren
    ReactChildReconciler.js:142:10
_reconcilerUpdateChildren
    ReactMultiChild.js:223:10
_updateChildren
    ReactMultiChild.js:366:6
updateChildren
    ReactMultiChild.js:352:25
receiveComponent
    ReactNativeBaseComponent.js:118:24
receiveComponent
    ReactReconciler.js:158:38
_updateRenderedComponentWithNextElement
    ReactCompositeComponent.js:1140:8
_updateRenderedComponent
    ReactCompositeComponent.js:1111:6
_performComponentUpdate
    ReactCompositeComponent.js:1032:36
updateComponent
    ReactCompositeComponent.js:915:8
receiveComponent
    ReactCompositeComponent.js:745:6
receiveComponent
    ReactReconciler.js:158:38
_updateRenderedComponentWithNextElement
    ReactCompositeComponent.js:1140:8
_updateRenderedComponent
    ReactCompositeComponent.js:1111:6
_performComponentUpdate
    ReactCompositeComponent.js:1032:36
updateComponent
    ReactCompositeComponent.js:915:8
receiveComponent
    ReactCompositeComponent.js:745:6
receiveComponent
    ReactReconciler.js:158:38
_updateRenderedComponentWithNextElement
    ReactCompositeComponent.js:1140:8
_updateRenderedComponent
    ReactCompositeComponent.js:1111:6
_performComponentUpdate
    ReactCompositeComponent.js:1032:36
updateComponent
    ReactCompositeComponent.js:915:8
receiveComponent
    ReactCompositeComponent.js:745:6
receiveComponent
    ReactReconciler.js:158:38
updateChildren
    ReactChildReconciler.js:142:10
_reconcilerUpdateChildren
    ReactMultiChild.js:223:10
_updateChildren
    ReactMultiChild.js:366:6
updateChildren
    ReactMultiChild.js:352:25
receiveComponent
    ReactNativeBaseComponent.js:118:24
receiveComponent
    ReactReconciler.js:158:38
_updateRenderedComponentWithNextElement
    ReactCompositeComponent.js:1140:8
_updateRenderedComponent
    ReactCompositeComponent.js:1111:6
_performComponentUpdate
    ReactCompositeComponent.js:1032:36
updateComponent
    ReactCompositeComponent.js:915:8
receiveComponent
    ReactCompositeComponent.js:745:6
receiveComponent
    ReactReconciler.js:158:38
_updateRenderedComponentWithNextElement
    ReactCompositeComponent.js:1140:8
_updateRenderedComponent
    ReactCompositeComponent.js:1111:6
_performComponentUpdate
    ReactCompositeComponent.js:1032:36
updateComponent
    ReactCompositeComponent.js:915:8
performUpdateIfNecessary
    ReactCompositeComponent.js:770:8
performUpdateIfNecessary
    ReactReconciler.js:210:46
runBatchedUpdates
    ReactUpdates.js:146:6
perform
    Transaction.js:150:24
perform
    Transaction.js:150:24
flushBatchedUpdates
    ReactUpdates.js:164:24
closeAll
    Transaction.js:221:29
perform
    Transaction.js:163:24
batchedUpdatesWithControlledComponents
    ReactGenericBatching.js:51:26
_receiveRootNodeIDEvent
    ReactNativeEventEmitter.js:105:40
receiveEvent
    ReactNativeEventEmitter.js:131:6
__callFunction
    MessageQueue.js:250:47
<unknown>
    MessageQueue.js:101:26
__guard
    MessageQueue.js:218:6
callFunctionReturnFlushedQueue
    MessageQueue.js:100:17
`

Any thought on this issue?

**Comment by blackxored** [comment]
You need a `MenuContext` wrapper AFAIK.

**Comment by huyhai** [comment]
it work for me, thank @blackxored

**Comment by laylafy** [comment]
Thank you @blackxored
