### ISSUE TITLE
Doesn't re-render onLayout

### ISSUE THREAD

**Issue by blackxored** [jaysoo/react-native-menu#42]
Having a hard time following the code, but it seems like whatever it's going on with measurement and layout doesn't happen when you rotate the device (and subsequently trigger an layout event that's supposed to be handled by `onLayout`. I've noticed this is set to be only called once, but this isn't the issue as it happens if I remove this line as well. 
The resulting problem is that the open menu's width is calculated fine on render, but if I rotate the device then the menu is no longer full width as I've set it to be.

**Comment by camloken** [comment]
I'm having a similar issue, but the menu completely disappears in landscape. Renders once in portrait mode, close the menu. Switch to landscape, click the menu, and it is rendered somewhere off the screen.
