### ISSUE TITLE
TouchableOpacity inside MenuTrigger

### ISSUE THREAD

**Issue by ndbroadbent** [jaysoo/react-native-menu#43]
I would like my trigger to dim when pressed, like a normal button. But it seems that this breaks react-native-menu. Is there any official way to do this?

It would be great if `MenuTrigger` could include this as a default option, because I think most people would it expect it to work this way. (When you press the trigger, the UI needs to show some feedback.)

**Comment by ndbroadbent** [comment]
I solved it by doing something like this:

```js
            <TouchableOpacity
              onPress={() => {
                this.props.toggleDropdownMenu(this.dropdownMenu.getName())
              }}
            >
              // ...
            </TouchableOpacity>
```

So I just skipped `MenuTrigger` and made my own using `TouchableOpacity`. I still think that `MenuTrigger` should have this behavior by default.

**Comment by furedal** [comment]
From the documentation:
```
const renderTouchable = () => <TouchableOpacity/>;
...
<MenuTrigger renderTouchable={renderTouchable}>
```

**Comment by Bfindlay** [comment]
Something is causing your main component to re-render thousands of times when the menu is open. You can test this by putting a console log in the render method and then opening the menu. I have not found a workaround yet.
