### ISSUE TITLE
High CPU consumption while menu is opened

### ISSUE THREAD

**Issue by sodik82** [jaysoo/react-native-menu#5]
CPU usage (reported by simulator) is near to 100% when the menu is opened even though there is no other activity (neither user activity nor "animation in progress").

In my application logs I can see that the applications keep re-rendering. (I have `MenuContext` at the application root as advised in documentation).

Another note: I can observe small lag between clicking of `MenuTrigger` and till the menu is opened. Might or might not be related to suboptimal CPU consumption.

**Comment by sodik82** [comment]
this story is likely to be related to https://github.com/jaysoo/react-native-menu/issues/9

**Comment by jaysoo** [comment]
@sodik82 Thanks for reporting. Just published `0.19.0 that solves this issue.

**Comment by sodik82** [comment]
unfortunately it seems that my issue was not resolved by the fix. Still hitting 100% CPU.

**Comment by jitenderchand1** [comment]
having the same issue. When menu is open render function call itself again and again
