### ISSUE TITLE
Android: Needs manual installation instructions

### ISSUE THREAD

**Issue by fogil** [jaysoo/react-native-menu#51]
Installation instructions are missing the other 4 steps required to install this library into a react-native app.

Step 1.)  npm i react-native-menu --save
This step only creates ./node_modules/react-native-menu.  Library is not built.  Library is not linked.  Library is not initialized in an android app.

Missing steps:
Step 2.) Modify ./android/settings.gradle
usually something like append to project inclusion list:

include ':name-of-library-goes-here'
project('name-of-library-goes-here').projectDir = new File(settingsDir, '../node_modules/name-of-library-goes-here')

Step 3.) Modify ./android/app/build.gradle
usually something like append to dependencies:

compile project(':name-of-library-goes-here')

Step 4.) Modify ./android/app/src/AndroidManifest.xml
If this project needs additional permission scopes, write down an example AndroidManifest.xml with the added permission scope included.

Step 5.) Modify ./android/app/src/main/java/PATH/TO/YOUR/MainApplication.java
Initialize the built library here; usually something like:

import com.jaysoo.RNMenu;
...
something, something, some Java code {
return Arrays.<ReactPackage>asList(
  ...,
  new RNMenu()
)
}

===================================
Current project installation leaves us in the dark.  Example project uses the source code in the same project so it's not helpful in showing us what the project inclusion files should look like. 

Otherwise, library's demo GIF looks nice, wish we can actually use the library though.

**Comment by fabriziomoscon** [comment]
this repo doesn't use any native code.
To install you just need to add the module with `npm` or `yarn`.
The steps you are mentioning would be necessary ONLY in case there were native code included into this library.
Please close this issue.
