### ISSUE TITLE
Use BackHandler instead of BackAndroid

### ISSUE THREAD

**Issue by jarvisluong** [jaysoo/react-native-menu#52]
I'm currently using react-native 0.45.1

Warning: BackAndroid is deprecated. Please use BackHandler instead.

**Comment by wasim2263** [comment]
same here.

**Comment by graam** [comment]
Same here too.

**Comment by jarvisluong** [comment]
I just found a pull request solving this: https://github.com/jaysoo/react-native-menu/pull/53

**Comment by scriptfans** [comment]
can you merge it and publish new version? thanks.

**Comment by jaysoo** [comment]
Published new version, which is compatible with latest RN.
