### ISSUE TITLE
Cannot read property 'makeName' of undefined.

### ISSUE THREAD

**Issue by SubhaPrince** [jaysoo/react-native-menu#56]
My sample code 

import Menu, {
  MenuContext,
  MenuOptions,
  MenuOption,
  MenuTrigger
} from "react-native-menu";
import React, { Component } from "react";
import { Text, TouchableOpacity } from "react-native";

import Button from "./Button";
const renderTouchable = () => <TouchableOpacity />;

export default class Gmenu extends Component {
  render() {
    return (
      <Menu>
        <MenuTrigger renderTouchable={renderTouchable}>
          <Text>Trigger</Text>
        </MenuTrigger>
        <MenuOptions>
          <MenuOption value={1} renderTouchable={renderTouchable}>
            <Text>One</Text>
          </MenuOption>
          <MenuOption value={2} renderTouchable={renderTouchable}>
            <Text>Two</Text>
          </MenuOption>
        </MenuOptions>
      </Menu>
    );
  }
}

**Comment by AnisDerbel** [comment]
+1

**Comment by WilliamMayo11** [comment]
I had this issue when I first integrated react-native-menu.

I was wrapping the parent component in a MenuContext tag, as the instructions suggest. Got that error.

To fix, I wrapped MenuContext around all the items in the component that holds the menu. So all react-native-menu related tags are on a single js file. Working fine now.

**Comment by SurajMDurgad** [comment]
@WilliamMayo11  Can you please give an example?

**Comment by k1115** [comment]
I have also the same issue
Plz give an example.

**Comment by freddessert** [comment]
@GreatPotter Going from `<MenuOption> <Text> This is some text </Text> </MenuOption>` To `<MenuContext><MenuOption> <Text> This is some text </Text> </MenuOption></MenuContext>`
