### ISSUE TITLE
Dropdown opening outside view port

### ISSUE THREAD

**Issue by gurveet** [jaysoo/react-native-menu#57]
I have dropdown at bottom of app. When we open it, it opens outside view port. So its not reachable.

![screen shot 2017-08-13 at 13 24 34](https://user-images.githubusercontent.com/30364923/29248024-eb43edb8-802a-11e7-8f05-8d874587e848.png)

**Comment by omerquyyum** [comment]
facing the same issue ... need to b fix asap

**Comment by omerquyyum** [comment]
check out this issue https://github.com/jaysoo/react-native-menu/issues/30 . solution

**Comment by hiteshsahu** [comment]
Same Issue Android

![image](https://user-images.githubusercontent.com/4076925/30030101-673c7e5a-91a9-11e7-8355-c57ddd23b4c9.png)
