### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Noitidart** [jaysoo/react-native-menu#67]
Hi there,

Is there any screenshots of how this looks for Android and on iOS? That's the first thing I look for before deciding to dig furhter.

**Comment by perhaps-yo** [comment]
[android-demo](https://github.com/jaysoo/react-native-menu/blob/master/packages/react-native-menu/android.demo.gif)

[ios-demo](https://github.com/jaysoo/react-native-menu/blob/master/packages/react-native-menu/ios.demo.gif)

**Comment by Noitidart** [comment]
Oh wow this is exactly what I need, thank you very much!
