### ISSUE TITLE
Parts of Dropdown Displaying Off-Screen

### ISSUE THREAD

**Issue by smilingkylan** [jaysoo/react-native-menu#69]
I believe I am using react-native-menu version 0.21.0. Unfortunately, in my ScrollView when the option button is pressed for an item that is toward the bottom of the scene, it causes parts of the menu to render outside of the viewport. See image:

![img_0383-modified](https://user-images.githubusercontent.com/6249205/30235088-11d67fc0-94b9-11e7-9947-740461f8e043.png)

How do you guys handle this? I wanted to get the position of the menu upon rendering but I do not seem to be able to do this (tried using `onLayout`), that way maybe I could adjust the positioning of the menu. I tried to get the positioning of the list item but it renders right away, before the user starts scrolling, so the initial positioning doesn't come in handy.

Do you guys have a way to avoid having the menu render outside of the viewport in these cases?

**Comment by yunlongz** [comment]
I have the same problem with you

**Comment by mohamed-alashry** [comment]
check out this issue [#30](https://github.com/jaysoo/react-native-menu/issues/30#issuecomment-305942329). solution
