### ISSUE TITLE
Missed demo

### ISSUE THREAD

**Issue by AlMel3000** [jaysoo/react-native-menu#76]
Hello!
As it is UI component image absence is very discouraging.

![2018-03-07_12-03-23](https://user-images.githubusercontent.com/19572431/37083234-feddf7b6-21ff-11e8-9f92-0ff689ec0866.png)

**Comment by lirenyeo** [comment]
from another issue:
[android demo](https://github.com/jaysoo/react-native-menu/blob/master/packages/react-native-menu/android.demo.gif)
[ios demo](https://github.com/jaysoo/react-native-menu/blob/master/packages/react-native-menu/ios.demo.gif)
